name: 'No Deploy Friday'
description: 'This GitHub Action will prevent you from deploying on Friday, Saturday, and Sunday'
inputs:
  timezone:
    description: 'Timezone'
    required: false
    default: 'UTC'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'clock'
  color: 'red'
