name: Deploy Core Hours

on:
  pull_request:
    branches:
      - 'main'

jobs:
  no_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy?
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Core Hours
      uses: ./
      with:
        timezone: 'America/New_York'
        dayStartHour: 10
        dayEndHour: 20
        deployFriday: false
