name: Deploy Core Hours

on:
  pull_request:
    branches:
      - 'main'

jobs:
  no_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy?
    steps:
    - name: Deploy Core Hours
      uses: quiltt/no-deploy-friday@v1.1
      with:
        timezone: 'America/New_York'
        dayStartHour: 10
        dayEndHour: 8
        deployFriday: false
